name: Build, Test and Publish

on: [push]

jobs:
  build-windows:
    env:
      DOTNET_ROOT: ""
    runs-on: windows-latest
    steps:
      - name: Print dotnet version before
        run: dotnet --version 
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: '3.1.101'
      - name: Print dotnet version after
        run: dotnet --version
      - name: List files
        run: ls $Env:DOTNET_ROOT
      - name: Print dotnet version using path
        run: pwsh $Env:DOTNET_ROOT/dotnet.exe --version
     

